### ISSUE TITLE
Adding gff_util.py ?

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/sequence_utils#12]
This is currently living in lib/galaxy/datatypes/util.
I think that would be another candidate that we could put in here, what do you think?
AFAIK it's only use on the tool side is in cufflinks, and that's really just two small functions, which could also be copied into the tool itself.

**Comment by jmchilton** [comment]
@mvdbeek I don't know - then the library would depend on bx. Wouldn't it be better to place those functions in bx?

**Comment by mvdbeek** [comment]
Yes, you're right.
