### ISSUE TITLE
Running conda-installed gx-fastq-paired-end-joiner on terminal

### ISSUE THREAD

**Issue by rassob** [galaxyproject/sequence_utils#17]
Hi,
I am trying to combine two fastq.gz files (paired-end) based on their sequence identifier. 
I installed the "galaxy_sequence_utils" package through the bioconda channel (version 1.1.3-py_0). The version of my Python is 3.6.2.

When I use the "gx-fastq-paired-end-joiner" command, however, I keep getting the error:

```
Traceback (most recent call last):
  File "/n/home13/miniconda3/envs/py1/bin/gx-fastq-paired-end-joiner", line 10, in <module>
    sys.exit(main())
  File "/n/home13/miniconda3/envs/py1/lib/python3.6/site-packages/galaxy_utils/sequence/scripts/fastq_paired_end_joiner.py", line 123, in main
    input1_filename = sys.argv[1]
IndexError: list index out of range
```
What is the proper usage of this tool in the command line?  I am trying:

``
gx-fastq-paired-end-joiner Read1.fastq.gz Read2.fastq.gz 
``

Thanks for your help! 

Rasim

**Comment by nsoranzo** [comment]
@rassob For an example on how to run this script, see:

https://github.com/galaxyproject/tools-devteam/blob/master/tool_collections/galaxy_sequence_utils/fastq_paired_end_joiner/fastq_paired_end_joiner.xml#L7

**Comment by samhimes92** [comment]
Hi, it looks like this link is down. Is there another place that I can find documentation/examples? I am also looking specifically to run the gx-fastq-paired-end-joiner.

**Comment by peterjc** [comment]
@samhimes92 see https://github.com/galaxyproject/tools-devteam/pull/548 - that example was moved to https://github.com/galaxyproject/tools-iuc/blob/main/tool_collections/galaxy_sequence_utils/fastq_paired_end_joiner/fastq_paired_end_joiner.xml - the command run was:

``
gx-fastq-paired-end-joiner '$input1_file' '${input1_file.extension[len('fastq'):]}' '$input2_file' '${input2_file.extension[len('fastq'):]}' '$output_file' $style '${paste_sequence}'
``

**Comment by peterjc** [comment]
I think a new issue on the https://github.com/galaxyproject/tools-iuc repository would be better, yes. Ideally could you share the example files with it?
