### ISSUE TITLE
Publish this library to PyPI

### ISSUE THREAD

**Issue by martenson** [galaxyproject/sequence_utils#3]

**Comment by peterjc** [comment]
Suggested by me on the mailing list (before I knew about this repository): https://lists.galaxyproject.org/pipermail/galaxy-dev/2017-January/025375.html

**Comment by jmchilton** [comment]
It lives - https://pypi.python.org/pypi/galaxy_sequence_utils.

**Comment by nsoranzo** [comment]
@jmchilton Should it be tagged as supporting Python>=3.3 too?

**Comment by jmchilton** [comment]
Yeah - it seemed a bit premature before.
