### ISSUE TITLE
Support compressed fastq throughout.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/sequence_utils#8]
Needed for upstream tools to support compressed file formats.

- [ ] Review and merge #11.
- [x] ~Review and merge https://github.com/galaxyproject/galaxy/pull/3550~
- [x] ~Review and merge https://github.com/galaxyproject/galaxy/pull/3553~
- [x] Update planemo with new XSD after #3553 so tool testing with ``decompress`` can be linted.
- [ ] Do a PyPI release with compressed IO support.
- [ ] Do a bioconda release.
- [ ] Compile a list of galaxy_sequence_utils dependent packages in tools-devteam to update (below)
- [ ] For each tool to update - add support for gz and bz2, add a test case and verify, update requirements, and delete tool_dependencies.xml.
  - [x] fastq_combiner - uses qual files and fasta files so doesn't need to be updated.
  - [ ] fastq_manipulation.xml https://github.com/galaxyproject/tools-devteam/pull/449
  - [ ] fastq_groomer
  - [ ] ...

**Comment by mvdbeek** [comment]
I can take that on if you want.

**Comment by jmchilton** [comment]
@mvdbeek I've done all the fun parts and now there is a lot of grunt work left. I tried to scope it out in above checklist - feel free to work on any part of it or let me know what I have done wrong up until this point.
